CarRentalSystem/src/main/java/mum/edu/carrentalsystem/model/Booking.java
package mum.edu.carrentalsystem.model;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
public class Booking implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@Id @GeneratedValue
	private int id;
	@Temporal(TemporalType.TIMESTAMP)
	private Date pickUpDate;
	@Temporal(TemporalType.TIMESTAMP)
	private Date dueDate;
	@Temporal(TemporalType.TIMESTAMP)
	private Date returnDate;
	private boolean isAvailable;
	private double fare;
	private boolean isPicked;
    private boolean isReturned;
    private boolean isDamaged;
    private boolean isPaid;
    private boolean isOverDue;
	@ManyToOne
	@JoinColumn(referencedColumnName="id")
	@JsonIgnore
	private Car car;
	@ManyToOne 
	@JoinColumn(referencedColumnName="id")
	@JsonIgnore
	private Users user;
	
/*	@OneToOne
	@JoinColumn(referencedColumnName="id")
	private CarType cartype;
*/	
	public int getId() {
		return id;
	}
	public Date getDueDate() {
		return dueDate;
	}
	public Date getReturnDate() {
		return returnDate;
	}
	public boolean isAvailable() {
		return isAvailable;
	}
	public double getFare() {
		return fare;
	}
	public Car getCar() {
		return car;
	}
/*	public Customer getCustomer() {
		return customer;
	}
*/	public void setId(int id) {
		this.id = id;
	}
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}
	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}
	public void setAvailable(boolean isAvailable) {
		this.isAvailable = isAvailable;
	}
	public void setFare(double fare) {
		this.fare = fare;
	}
	public void setCar(Car car) {
		this.car = car;
	}
/*	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
*/	public Date getPickUpDate() {
		return pickUpDate;
	}
	public void setPickUpDate(Date pickUpDate) {
		this.pickUpDate = pickUpDate;
	}
	public boolean isPicked() {
		return isPicked;
	}
	public boolean isReturned() {
		return isReturned;
	}
	public boolean isDamaged() {
		return isDamaged;
	}
	public boolean isPaid() {
		return isPaid;
	}
	public boolean isOverDue() {
		return isOverDue;
	}
	public void setPicked(boolean isPicked) {
		this.isPicked = isPicked;
	}
	public void setReturned(boolean isReturned) {
		this.isReturned = isReturned;
	}
	public void setDamaged(boolean isDamaged) {
		this.isDamaged = isDamaged;
	}
	public void setPaid(boolean isPaid) {
		this.isPaid = isPaid;
	}
	public void setOverDue(boolean isOverDue) {
		this.isOverDue = isOverDue;
	}
	public Users getUser() {
		return user;
	}
	public void setUser(Users user) {
		this.user = user;
	}
	@Override
	public String toString() {
		return "Booking [id=" + id + ", pickUpDate=" + pickUpDate + ", dueDate=" + dueDate + ", returnDate="
				+ returnDate + ", isAvailable=" + isAvailable + ", fare=" + fare + ", isPicked=" + isPicked
				+ ", isReturned=" + isReturned + ", isDamaged=" + isDamaged + ", isPaid=" + isPaid + ", isOverDue="
				+ isOverDue + ", car=" + car + ", user=" + user + "]";
	}
	
}

CarRentalSystem/src/main/java/mum/edu/carrentalsystem/model/Car.java
package mum.edu.carrentalsystem.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import javax.validation.constraints.Future;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
public class Car implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	@Id
	@GeneratedValue
	private long id;

	@NotEmpty
	private String registrationId;

	@Temporal(TemporalType.TIMESTAMP)
	private Date registeredDate;

	@Temporal(TemporalType.TIMESTAMP)
	private Date expirationDate;
	@Valid
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(referencedColumnName = "id")
	//@JsonIgnore
	private CarType cartype;
	@NotEmpty
	private String description;
	@Lob
	private byte[] picture;
	private transient CommonsMultipartFile carPicture = null;
	
	@OneToMany(mappedBy = "car", cascade = CascadeType.ALL)
	@JsonIgnore
	private List<Booking> booking = new ArrayList<Booking>();

	public Car() {
		super();
	}

	/*
	 * public Car(String registrationID, String model, String year, Category
	 * category) { this.registrationId = registrationID; this.model = model;
	 * this.year = year; this.category = category; }
	 */
	public String getUrlPicture() {
		if (this.picture != null)
			return "data:image/jpg;base64," + Base64.getEncoder().encodeToString(this.picture);
		return "";
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRegistrationId() {
		return registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	public CarType getCartype() {
		return cartype;
	}

	public void setCartype(CarType cartype) {
		this.cartype = cartype;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<Booking> getBooking() {
		return booking;
	}

	public void setBooking(List<Booking> booking) {
		this.booking = booking;
	}

	public byte[] getPicture() {
		return picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
		/* this.pictureName = picture.getOriginalFilename(); */
	}

	public Date getRegisteredDate() {
		return registeredDate;
	}

	public Date getExpirationDate() {
		return expirationDate;
	}

	public void setRegisteredDate(Date registeredDate) {
		this.registeredDate = registeredDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public CommonsMultipartFile getCarPicture() {
		return carPicture;
	}

	public void setCarPicture(CommonsMultipartFile carPicture) {
		this.carPicture = carPicture;
	}

	/*
	 * @Override public String toString() { return "Car [id=" + id +
	 * ", registrationId=" + registrationId + ", registeredDate=" +
	 * registeredDate + ", expirationDate=" + expirationDate + ", cartype=" +
	 * cartype + ", description=" + description + ", booking=" + booking + "]";
	 * }
	 */

}

CarRentalSystem/src/main/java/mum/edu/carrentalsystem/controller/BookingController.java
package mum.edu.carrentalsystem.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import mum.edu.carrentalsystem.model.Booking;
import mum.edu.carrentalsystem.model.Car;
import mum.edu.carrentalsystem.model.Users;
import mum.edu.carrentalsystem.service.BookingService;
import mum.edu.carrentalsystem.service.CarService;

@Controller
public class BookingController {

	@Autowired
	private CarService carService;

	@Autowired
	public void setCarService(CarService carService) {
		this.carService = carService;
	}

	@Autowired
	private BookingService bookingService;

	@Autowired
	public void setBookingService(BookingService bookingService) {
		this.bookingService = bookingService;
	}

	@RequestMapping(value = "/booking", method = RequestMethod.GET)
	public String bookingPage(@ModelAttribute("booking") Booking booking, Model model) {
		List<Car> listCar = new ArrayList<Car>();
		listCar = carService.getAllCars();
		List<Car> listCarEconomy = new ArrayList<Car>();
		List<Car> listCarStandard = new ArrayList<Car>();
		List<Car> listLuxuary = new ArrayList<Car>();
		List<Car> listBusiness = new ArrayList<Car>();
		for (Car c : listCar) {
			// System.out.println(c.getCartype().getCategory());
			if (c.getCartype().getCategory().toString().equals("ECONOMIC")) {
				listCarEconomy.add(c);
			} else if (c.getCartype().getCategory().toString().equals("STANDARD")) {
				listCarStandard.add(c);
			} else if (c.getCartype().getCategory().toString().equals("LUXUARY")) {
				listLuxuary.add(c);
			} else
				listBusiness.add(c);

		}
		model.addAttribute("listCarEconomy", listCarEconomy);
		model.addAttribute("listBusiness", listBusiness);
		model.addAttribute("listLuxuary", listLuxuary);
		model.addAttribute("listCarStandard", listCarStandard);
		model.addAttribute("listCar", listCar);
		model.addAttribute("booking", booking);
		System.out.println(booking);
		return "booking";

		/*
		 * User user =
		 * (User)SecurityContextHolder.getContext().getAuthentication().
		 * getPrincipal(); String name = user.getUsername(); System.out.println(
		 * "This is user:"+user);
		 */

	}

	@RequestMapping(value = "/booking", method = RequestMethod.POST)
	public @ResponseBody String redirectBookingPage(@ModelAttribute("booking") Booking booking, int id, Model model) {

		System.out.println("Here you go with CarId: " + id);
		Car car = carService.get(id);
		// User user = (User)
		// SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		// String name = user.getUsername();
		booking.setCar(car);
		Users currentUser = new Users();
		// booking.setUser(user);
		// System.out.println("This is user:" + user);

		return "";

		// System.out.println("Here you go");
		// System.out.println(booking.getCar().getId());
		// bookingService.newBooking(booking);
		// System.out.println("I am herer");
		// return "redirect:/";
	}


/*
 * @RequestMapping(value = "/booking", method = RequestMethod.POST) public
 * String redirectBookingPage(@ModelAttribute("booking") Booking booking, Model
 * model) { System.out.println("Here you go");
 * System.out.println(booking.getCar().getId());
 * bookingService.newBooking(booking); System.out.println("I am herer"); return
 * "redirect:/"; }
 */

/*
 * @RequestMapping(value = {"/bookingcarlist"}, method = RequestMethod.GET)
 * public String bookingCarlist(Booking booking, Model model) {
 * model.addAttribute("bookingcarlist",booking ); return "bookingcarlist"; }
 */
/*
 * @RequestMapping(value = { "/bookingcarlist" }, method = RequestMethod.POST)
 * public String redirectBookingCarlist(@ModelAttribute("booking") Booking
 * booking, Model model) { // model.addAttribute("bookingcarlist",booking );
 * System.out.println("I am Here" + booking.getFare()); return "bookingconfirm";
 * }
 * 
 * 
 * @RequestMapping(value = {"/bookingconfirm"}, method = RequestMethod.GET)
 * public String bookingconfirm(Booking booking, Model model) {
 * model.addAttribute("bookingconfirm",booking ); return "bookingconfirm"; }
 * 
 * 
 * @RequestMapping(value = { "/bookingconfirm" }, method = RequestMethod.POST)
 * public String redirectBookingconfirm(@ModelAttribute("booking") Booking
 * booking, Model model) { // model.addAttribute("bookingconfirm",booking );
 * System.out.println("I am Hereeeee" + booking.getFare()); return "booking"; }
 */
/*
 * @ModelAttribute("category") public Category[] getCategory() { return
 * Category.values(); }
 */
}

CarRentalSystem/src/main/java/mum/edu/carrentalsystem/controller/HomeController.java
package mum.edu.carrentalsystem.controller;

import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import mum.edu.carrentalsystem.model.Car;
import mum.edu.carrentalsystem.service.CarService;

/**
 * Handles requests for the application home page.
 */
@Controller
public class HomeController {
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	private CarService carService;

	@Autowired
	public void setCarService(CarService carService) {
		this.carService = carService;
	}
	@RequestMapping(value = {"/","/home"}, method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);
		
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);
		
		String formattedDate = dateFormat.format(date);
		List<Car> carList = carService.getAllCars();
		model.addAttribute("serverTime", formattedDate );
		model.addAttribute("carList", carList);
		System.out.println(carList);
		return "homepage";
	}
	
}

CarRentalSystem/src/main/webapp/WEB-INF/views/booking.jsp

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

This is Booking Page. Here Location and Date Selection can be done.
<c:url var="home" value="/" scope="request" />
<form:form modelAttribute="booking">
	<div id="bookingCardate">
		From:
		<form:input path="pickUpDate" type="text" class="datepicker" />
		To:
		<form:input path="dueDate" type="text" class="datepicker" />
		<br> Type:
		<form:select path="car.cartype.category" id="carCategory"
			onchange="searchCat()" class="btn btn-primary dropdown-toggle">
			<option value="">select category</option>
			<form:options items="${category}" />
		</form:select>

		<div class="container-fluid" id="parent"></div>
		<%-- <img alt="sfdfs" src="${listCarEconomy[0].urlPicture}"> --%>
		<script>
			$("#carCategory")
					.change(
							function() {
								var selected = $("#carCategory option:selected")
										.text();
								var selectedLoop = null;
								var html = null;
								if (selected == "ECONOMIC") {
									var html = '<div class="col-md-12"><c:forEach items="${listCarEconomy}" var="car"><div class="col-md-4"><div class="col-md-12"><div class="thumbnail"><img alt="sfdfs" style="width:150px;height:150px" src="${car.urlPicture}"><div class="caption"><b>Brand: ${car.cartype.brand}<br>Year: ${car.cartype.year}<br>Model: ${car.cartype.model}<br>Seats: ${car.cartype.seats}<br>Air Conditioner: ${car.cartype.airConditioner}<br>Daily Rate:${car.cartype.rate.dailyRate}<br>Weekly Rate:${car.cartype.rate.weeklyRate}<br>Monthly Rate:${car.cartype.rate.monthlyRate}<b><br>Description: ${car.description}<br><input class="btn btn-primary"  role="button"  onclick="myFunction(${car.id})" value = "Book Now"/></div></div></div></div></c:forEach></div>';
								} else if (selected == "LUXUARY") {
									var html = '<div class="col-md-12"><c:forEach items="${listLuxuary}" var="car"><div class="col-md-4"><div class="col-md-12"><div class="thumbnail"><img alt="sfdfs" style="width:150px;height:150px" src="${car.urlPicture}"><div class="caption"><b>Brand: ${car.cartype.brand}<br>Year: ${car.cartype.year}<br>Model: ${car.cartype.model}<br>Seats: ${car.cartype.seats}<br>Air Conditioner: ${car.cartype.airConditioner}<br>Daily Rate:${car.cartype.rate.dailyRate}<br>Weekly Rate:${car.cartype.rate.weeklyRate}<br>Monthly Rate:${car.cartype.rate.monthlyRate}<b><br>Description: ${car.description}<br><button class="btn btn-primary" role="button"  onclick="myFunction()">Book Now</button></div></div></div></div></c:forEach></div>';
								} else if (selected == "STANDARD") {
									var html = '<div class="col-md-12"><c:forEach items="${listCarStandard}" var="car"><div class="col-md-4"><div class="col-md-12"><div class="thumbnail"><img alt="sfdfs" style="width:150px;height:150px" src="${car.urlPicture}"><div class="caption"><b>Brand: ${car.cartype.brand}<br>Year: ${car.cartype.year}<br>Model: ${car.cartype.model}<br>Seats: ${car.cartype.seats}<br>Air Conditioner: ${car.cartype.airConditioner}<br>Daily Rate:${car.cartype.rate.dailyRate}<br>Weekly Rate:${car.cartype.rate.weeklyRate}<br>Monthly Rate:${car.cartype.rate.monthlyRate}<b><br>Description: ${car.description}<br><button class="btn btn-primary" role="button"  onclick="myFunction()">Book Now</button></div></div></div></div></c:forEach></div>';
								} else {
									var html = '<div class="col-md-12"><c:forEach items="${listBusiness}" var="car"><div class="col-md-4"><div class="col-md-12"><div class="thumbnail"><img alt="sfdfs" style="width:150px;height:150px" src="${car.urlPicture}"><div class="caption"><b>Brand: ${car.cartype.brand}<br>Year: ${car.cartype.year}<br>Model: ${car.cartype.model}<br>Seats: ${car.cartype.seats}<br>Air Conditioner: ${car.cartype.airConditioner}<br>Daily Rate:${car.cartype.rate.dailyRate}<br>Weekly Rate:${car.cartype.rate.weeklyRate}<br>Monthly Rate:${car.cartype.rate.monthlyRate}<b><br>Description: ${car.description}<br><button class="btn btn-primary" role="button"  onclick="myFunction()">Book Now</button></div></div></div></div></c:forEach></div>';
								}
								$("#child1").remove()
								$("#parent").append(
										'<div id="child1">' + html + '</div>');
							});

			function myFunction(carId) {

				$.ajax({
					url : "${home}booking?id=" + carId,
					type : "POST",
					//data : JSON.stringify(json),
					dataType : 'json',
					//contentType : 'application/json',   

					success : function(val) {
						
					},
					error : function(err) {
						
					}
				});
			}
		</script>
	</div>
</form:form>

<%-- <a href="${pageContext.request.contextPath}/bookingcarlist">SelectCar</a> --%>

CarRentalSystem/src/main/webapp/WEB-INF/views/bookingcarlist.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	This page will show the List of Car.
	<%--  <h3>${booking.fare}</h3> --%>
	<form:form method="post" modelAttribute="booking"
		action="bookingcarlist">
		<table>
			<form:hidden path="dueDate" />
			<form:hidden path="pickUpDate" />
<%-- 			<c:forEach items="booking.car" var="car" varStatus="status">
				<td><label>RegistrationId</label></td>
				<td><form:input path="car[0].registrationId" type="text" /></td>
			</c:forEach>
 --%>		</table>
		<button type="submit">Next</button>
	</form:form>

	<a href="${pageContext.request.contextPath}/booking">Back</a>
	<a href="${pageContext.request.contextPath}/bookingconfirm">Next</a>
</body>
</html>

CarRentalSystem/src/main/webapp/WEB-INF/views/bookingconfirm.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<a href="${pageContext.request.contextPath}/bookingcarlist">Back</a>
<a href="${pageContext.request.contextPath}/user">Confirm</a>
</body>
</html>

CarRentalSystem/src/main/webapp/WEB-INF/views/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page session="false"%>
<h1>Welcome to Car Rental System.</h1>

<P>${serverTime}.</P>
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-4" id="ECONOMIC">
			<h2>ECONOMIC</h2>
			<c:forEach items="${carList}" var="car">
				<c:if test="${car.cartype.category=='ECONOMIC'}">
					<div class="thumbnail">
						<div class="caption">
							<h4>
								Model: ${car.cartype.model }<br>Brand: ${car.cartype.brand }<br>Year:
								${car.cartype.year }
							</h4>
						</div>
						<img alt="ECONOMIC image not found"
							style="width: 350px; height: 350px" src="${car.urlPicture}">
						<div class="caption">
							<p>Details: ${car.description}</p>
						</div>
					</div>
				</c:if>
			</c:forEach>
		</div>
		<div class="col-sm-6 col-md-4" id="LUXUARY">
			<h2>LUXUARY</h2>
			<c:forEach items="${carList}" var="car">
				<c:if test="${car.cartype.category=='LUXUARY'}">
					<div class="thumbnail">
						<div class="caption">
							<h4>
								Model: ${car.cartype.model }<br>Brand: ${car.cartype.brand }<br>Year:
								${car.cartype.year }
							</h4>
						</div>
						<img alt="LUXUARY image not found"
							style="width: 350px; height: 350px" src="${car.urlPicture}">
						<div class="caption">
							<p>Details: ${car.description}</p>
						</div>
					</div>
				</c:if>

			</c:forEach>
		</div>
		<div class="col-sm-6 col-md-4" id="STANDARD">
			<h2>STANDARD</h2>
			<c:forEach items="${carList}" var="car">

				<c:if test="${car.cartype.category=='STANDARD'}">
					<div class="thumbnail">
						<div class="caption">
							<h4>
								Model: ${car.cartype.model }<br>Brand: ${car.cartype.brand }<br>Year:
								${car.cartype.year }
							</h4>
						</div>

						<img alt="STANDARD image not found"
							style="width: 350px; height: 350px" src="${car.urlPicture}">
						<div class="caption">
							<p>Details: ${car.description}</p>
						</div>
					</div>
				</c:if>
			</c:forEach>
		</div>
		<div class="col-sm-6 col-md-4" id="BUSINESS">
			<h2>BUSINESS</h2>
			<c:forEach items="${carList}" var="car">
				<c:if test="${car.cartype.category=='BUSINESS'}">
					<div class="thumbnail">
						<div class="caption">
							<h4>
								Model: ${car.cartype.model }<br>Brand: ${car.cartype.brand }<br>Year:
								${car.cartype.year }
							</h4>
						</div>

						<img alt="BUSINESS image not found"
							style="width: 350px; height: 350px" src="${car.urlPicture}">
						<div class="caption">
							<p>Details: ${car.description}</p>
						</div>
					</div>
				</c:if>
			</c:forEach>
		</div>

	</div>

</div>

<br />
<br />
<br />
<br />


CarRentalSystem/src/main/webapp/WEB-INF/views/test.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<h1>This is for test and being used for testing</h1>
</body>
</html>